# App configuration
spring.application.name=wishlist

server.port=6543

# OAuth2 Server Cofnig (Keycloak) Must be updated for production use 
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/testing

# DEBUG JWT Processing (DELETE IN PRODUCTION)
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.jwt=TRACE

# OpenAPI Docs config
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/docs/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs/api-ui.html